input("noun")
input("crazy state")
input("verb")
input("noun")
input("people's name")
input("verb")
input("noun")
input("verb")
input("noun")
input("part of the body")
input("adjective")
input("relative")
input("activity")
input("chain resturant")
input("an adjective past tense")
input("month")
input("verb")
input("noun")