noun1=input("noun")
state1=input("crazy state")
verb1=input("verb")
noun2=input("noun")
name1=input("people's name")
verb2=input("verb")
noun3=input("noun")
verb3=input("verb")
input("noun")
input("part of the body")
input("adjective")
input("relative")
input("activity")
input("chain resturant")
input("an adjective past tense")
input("month")
input("verb")
input("noun")
